name: CI-WORKFLOW

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buil-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build
        run: echo "Build successful"

      - name: Test
        run: echo "Test successful"

      - name: Artifact upload
        uses: actions/upload-artifact@v7
        with:
          name: artifact-1
          path: |
            .github/workflows/*.yml

      - name: Deploy
        run: echo "my code is deployed"
